#!/bin/bash
# This wrapper uses 110GB heap

java -Xmx56g -Xms56g -Xmn11g \
    -cp ../libraries/SystemDS.jar:../libraries/lib/* \
    -Dlog4j.configuration=file:../libraries/log4j-silent.properties \
    org.apache.sysds.api.DMLScript \
    -exec singlenode \
    -debug \
    -config ../libraries/SystemDS-config.xml \
    "$@"
